spring.application.name=agenticai
spring.ai.openai.api-key=sk-ijklmnopqrstuvwxijklmnopqrstuvwxijklmnop
spring.ai.openai.image.options.model=gpt-4.1
server.port=9090
#Cette propriete pour logger tous les messages intercepter par le client (interface chatClient)
logging.level.org.springframework.ai.chat.client.advisor=DEBUG